# Generated by Django 5.1.7 on 2025-05-10 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0003_platformanalytics_announcement_contentanalytics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='status',
            field=models.CharField(choices=[('STRUGGLING', 'I need help with something specific'), ('EXPLORING', 'Just exploring mental health topics'), ('MAINTAINING', 'Doing okay, maintaining my wellbeing'), ('CELEBRATING', 'Feeling great and want to celebrate!')], default='EXPLORING', help_text='General state of the user when recording this entry', max_length=20),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='related_quiz',
            field=models.ForeignKey(blank=True, help_text='Optional link to a quiz attempt that might relate to this mood', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentalhealth.quizattempt'),
        ),
        migrations.AddIndex(
            model_name='moodentry',
            index=models.Index(fields=['user', 'recorded_at'], name='mentalhealt_user_id_fe43fd_idx'),
        ),
        migrations.AddIndex(
            model_name='moodentry',
            index=models.Index(fields=['status'], name='mentalhealt_status_3a2bc0_idx'),
        ),
        migrations.AddIndex(
            model_name='moodentry',
            index=models.Index(fields=['mood_level'], name='mentalhealt_mood_le_010d65_idx'),
        ),
    ]
