# Generated by Django 5.1.7 on 2025-05-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0004_moodentry_status_alter_moodentry_related_quiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='device_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
